### ISSUE TITLE
fix: Support for wake-up alarm for STM32F1xx and STM32F2xx

### ISSUE THREAD

**Issue by tenhovelukas** [withthegrid/mbed-os#6]
Add support for target that doesn't have subseconds in stm32f2xx_hal_rtc.h

**Comment by vidavidorra** [comment]
The only way to configure the wake-up alarm in Mbed OS is using the `LOWPOWERTIMER` device configuration. A proper implementation for targets that don't actually have the low-power timer would be adding a file in the specific target implementing `rtc_set_wake_up_timer`, `rtc_deactivate_wake_up_timer` and some kind of IRQ.

**Comment by vidavidorra** [comment]
Fixed in cf70b3c17
